### PR TITLE
uniform distribution [-1,1]

### PR DESCRIPTION
**Pull request by vavrines**
add support for uniform distribution [-1,1] with density, measure and orthopoly implementations.

### CODE REVIEW

**Comment by timueh** [comment]
Can you please add tests, e.g. checking for the correct variance. The existing test files should give you an idea of how and what to test for. Thanks.

**Comment by timueh** [comment]
I guess we should be compliant with current naming of `Uniform01OrthoPoly`, hence call the polynomial `Uniform11OrthoPoly`?! Same for the weight function etc.

**Comment by vavrines** [comment]
> I guess we should be compliant with current naming of `Uniform01OrthoPoly`, hence call the polynomial `Uniform11OrthoPoly`?! Same for the weight function etc.

The underline meant to denote minus.
I agree we can make it "11" directly.

**Comment by timueh** [comment]
Ah, my bad! Mh.. tough. We need a third person to take a vote. 😆

**Comment by timueh** [comment]
Does it work directly with `Uniform-11OrthoPoly`?

**Comment by timueh** [comment]
Let's got with your suggestion and keep the underscore as a minus. In any case, can you add the new polynomial to [the documentation](https://timueh.github.io/PolyChaos.jl/stable/type_hierarchy/) and make a note box there saying that the underscore is to be understood as a minus?

thx!

**Comment by vavrines** [comment]
The minus cannot be used to name variable directly. 
Okay let's keep it. I'll add the doc.

**Pull request merged**
