### PR TITLE
Remove StaticArrays compat bound

### PR DESCRIPTION
**Pull request by anandijain**
All the tests pass locally for me so there should be no problem.

Before removing this, adding PolyChaos was dropping my StaticArrays and a whole bunch of other downstream deps.

### CODE REVIEW

**Comment by timueh** [comment]
Thanks for the pointer!

I apologize for the inconveniences. Dependency hell is..well..hell!

Can you say once more what exactly was *not* working?

**Comment by anandijain** [comment]
It basically dropped all of the Array packages. I'm not exactly sure where though. @timueh 
```julia 
(@v1.6) pkg> add PolyChaos
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [8d666b04] + PolyChaos v0.2.3
  [90137ffa] ↓ StaticArrays v1.0.1 ⇒ v0.12.5
  [0c5d862f] ↑ Symbolics v0.1.4 ⇒ v0.1.5
  [bd369af6] ↑ Tables v1.3.2 ⇒ v1.4.0
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [c75e803d] + AdaptiveRejectionSampling v0.1.1
  [4c555306] ↓ ArrayLayouts v0.6.2 ⇒ v0.4.11
  [aae01518] ↓ BandedMatrices v0.16.5 ⇒ v0.15.25
  [8e7c35d0] ↓ BlockArrays v0.14.5 ⇒ v0.12.14
  [ffab5731] ↓ BlockBandedMatrices v0.10.3 ⇒ v0.9.5
  [31c24e10] ↓ Distributions v0.24.15 ⇒ v0.23.12
  [1a297f60] ↓ FillArrays v0.11.5 ⇒ v0.9.7
  [d54b0c1a] + GaussQuadrature v0.5.4
  [5078a376] ↓ LazyArrays v0.20.9 ⇒ v0.18.1
  [d7e5e226] ↓ LazyBandedMatrices v0.5.2 ⇒ v0.3.6
  [a3b82374] ↓ MatrixFactorizations v0.8.2 ⇒ v0.6.1
  [90014a1f] ↓ PDMats v0.11.0 ⇒ v0.10.1
  [8d666b04] + PolyChaos v0.2.3
  [aedffcd0] ↑ Static v0.2.2 ⇒ v0.2.3
  [90137ffa] ↓ StaticArrays v1.0.1 ⇒ v0.12.5
  [0c5d862f] ↑ Symbolics v0.1.4 ⇒ v0.1.5
  [bd369af6] ↑ Tables v1.3.2 ⇒ v1.4.0
```
If I try to force SArrays to be version 1.0.1 I get 
```julia 
(@v1.6) pkg> add StaticArrays@1.0.1
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Distributions [31c24e10]:
 Distributions [31c24e10] log:
 ├─possible versions are: 0.16.0-0.24.15 or uninstalled
 ├─restricted by compatibility requirements with Symbolics [0c5d862f] to versions: 0.23.0-0.24.15
 │ └─Symbolics [0c5d862f] log:
 │   ├─possible versions are: 0.1.0-0.1.5 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.1.5
 ├─restricted by compatibility requirements with StaticArrays [90137ffa] to versions: [0.16.0-0.23.11, 0.24.5-0.24.15] or uninstalled, leaving only versions: [0.23.0-0.23.11, 0.24.5-0.24.15]
 │ └─StaticArrays [90137ffa] log:
 │   ├─possible versions are: 0.8.0-1.0.1 or uninstalled
 │   └─restricted to versions 1.0.1 by an explicit requirement, leaving only versions 1.0.1
 └─restricted by compatibility requirements with PolyChaos [8d666b04] to versions: 0.16.0-0.22.6 — no versions left
   └─PolyChaos [8d666b04] log:
     ├─possible versions are: 0.1.0-0.2.3 or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.2.3
     └─restricted by compatibility requirements with StaticArrays [90137ffa] to versions: 0.1.0-0.2.2 or uninstalled, leaving only versions: 0.1.0-0.2.2
       └─StaticArrays [90137ffa] log: see above
```

**Comment by anandijain** [comment]
A new version probably needs to be tagged for the compat stuff to be fixed.

**Comment by timueh** [comment]
Thanks. It looks like some other packages could/should be updated too with a new version v0.2.4

**Comment by GunnarFarneback** [comment]
The master branch had already bumped StaticArrays compat to include version 1 in #45, so the removing the compat bound makes no difference at all to the problem reported here, which was that version 2.3 was not compatible with StaticArrays 1.0.

Effective solutions are to wait for a new version 2.4, add `PolyChaos#master`, or `dev PolyChaos`.

**Pull request merged**
