### PR TITLE
Fix compatibility issue

### PR DESCRIPTION
**Pull request by vavrines**
Current setup in Project.toml can trigger incompatibility in Julia 1.5. Fixed in this branch.

### CODE REVIEW

**Comment by timueh** [comment]
Thanks for the pointer. This is a tedious thing to get right in my experience (of course, I might do something wrong). I remember I played a long time to get the current version of `Project.toml` to compile with Julia 1.1 - 1.3. I also wanted to use the `>=` notation, but `SpecialFunctions` always plays the devil...

Here's a *solution*: check what versions of the required packages works for Julia 1.4 and 1.5, and then add them to `Project.toml` manually. 

As I said -- unfortunately, I found no better way around yet.. =/

**Comment by vavrines** [comment]
> Thanks for the pointer. This is a tedious thing to get right in my experience (of course, I might do something wrong). I remember I played a long time to get the current version of `Project.toml` to compile with Julia 1.1 - 1.3. I also wanted to use the `>=` notation, but `SpecialFunctions` always plays the devil...
> 
> Here's a _solution_: check what versions of the required packages works for Julia 1.4 and 1.5, and then add them to `Project.toml` manually.
> 
> As I said -- unfortunately, I found no better way around yet.. =/

Yes, something still goes wrong in travis. I think it's related with SpecialFunctions. I'll have a look there.

**Comment by timueh** [comment]
Thanks a lot!

SpecialFunctions has given me a lot of headaches to get right.. Perhaps it works if you use the old entry from `Project.toml` for `SpecialFunctions`?

**Comment by vavrines** [comment]
Quite weird: I copied the old Project.toml exactly into my fork, but the travis build stills fails for julia 1.0 and 1.1...

**Comment by timueh** [comment]
Are you positive it's the same toml file? The problem is and remains

```ERROR: LoadError: UndefVarError: loggamma not defined```

which is due to SpecialFunctions... =/

**Comment by vavrines** [comment]
> Are you positive it's the same toml file? The problem is and remains
> 
> `ERROR: LoadError: UndefVarError: loggamma not defined`
> 
> which is due to SpecialFunctions... =/

should be the same since I directly ctrl c/v there..

**Comment by timueh** [comment]
This is strange indeed. I guess we should ask for help on discourse? As I said, I can't really count the hours I spent trying to fix this..

I am still on paternal leave and can't really take care of it. If you want, go ahead and post it. If you don't want to---which would of course be fine---I'll go ahead in the next weeks.

**Comment by timueh** [comment]
I think a reasonable solution is to take the version of the `Project.toml` that works for Julia >= 1.3, and stop supporting Julia 1.0 and 1.1.. It's kind of a *cheap* way out but unless you want to spend hours on fixing the toml that's what I suggest.. ^^

**Comment by vavrines** [comment]
> I think a reasonable solution is to take the version of the `Project.toml` that works for Julia >= 1.3, and stop supporting Julia 1.0 and 1.1.. It's kind of a _cheap_ way out but unless you want to spend hours on fixing the toml that's what I suggest.. ^^

That's also exactly what I was thinking about.
SpecialFunctions made a quite big change from 0.7 to 0.10 due to some built-in functions in Julia, and now they only do test on Julia 1.4. As other dependencies update, it could get harder in the future for the compatibility. Supporting 1.3 upwards is a good idea.

**Comment by timueh** [comment]
That should be fairly straightfoward then. All I need to remember is to also compile the documentation with Julia 1.3 or above.

I hope to get this done soon.

Thanks for the input!

**Comment by timueh** [comment]
i released polychaos as version 0.2.3 which fixes the issues you mentioned.

once again, thanks.

**Pull request closed without merging**
